name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cargo Cache
        id: cargo-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install
        run: cargo build

      - name: Build
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install trunk
          trunk build --release

      - name: AWS login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-1
          role-to-assume: arn:aws:iam::177613294657:role/pixatarDeploy

      - name: Update site
        run: aws --region us-west-1 s3 sync --delete ./dist s3://pixatar-djmetzle-io/

      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id E1R22IYXB9TRJ1 --paths "/*"
